name: Pull docker image
description: Pull docker image

inputs:
  image:
    description: The docker image to pull
    required: true
    default: kmake-image:latest

  github_token:
    description: The GitHub token to use for authentication
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone kmake-image
      shell: bash
      run: |
        git clone https://github.com/qualcomm-linux/kmake-image.git

    - name: Build docker image
      shell: bash
      run: |
        cd kmake-image
        docker build . -t kmake-image
