name: PR email addresses checker

on:
  pull_request:

jobs:
  pr-check-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR emails
        uses: qualcomm/commit-emails-check-action@main
