name: pre_merge
on:
  pull_request_target:
    branches:
      - test-definition

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      docker_image: kmake-image:latest

  test:
    needs: [build]
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      docker_image: kmake-image:latest
